# Generated by Django 2.1.1 on 2018-10-29 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('auth_name', models.CharField(max_length=20)),
                ('level', models.SmallIntegerField()),
                ('path', models.FilePathField()),
                ('pid', models.ForeignKey(db_column='pid', on_delete=django.db.models.deletion.CASCADE, to='permissions.Permission')),
            ],
            options={
                'db_table': 'permission',
            },
        ),
    ]
