# Generated by Django 2.1.1 on 2018-11-05 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('course_schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDoneInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_data', models.FilePathField(null=True)),
                ('commit_date', models.DateTimeField(null=True)),
                ('score', models.FloatField(null=True)),
                ('remark_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
            options={
                'db_table': 'lab_result',
            },
        ),
        migrations.CreateModel(
            name='LabTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='试验', max_length=20, unique=True)),
                ('data', models.FilePathField(default=None, path='/')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 10, 38, 8, 326968))),
                ('deadline', models.DateTimeField(default=datetime.datetime(2018, 11, 5, 10, 38, 8, 326968))),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_schedule.Schedule')),
            ],
            options={
                'db_table': 'lab_task',
            },
        ),
        migrations.AddField(
            model_name='labdoneinfo',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.LabTask'),
        ),
    ]
