# Generated by Django 2.1.1 on 2018-11-05 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtask',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 10, 40, 38, 662551)),
        ),
        migrations.AlterField(
            model_name='labtask',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 5, 10, 40, 38, 662551)),
        ),
        migrations.AlterModelTable(
            name='labdoneinfo',
            table='lab_done_info',
        ),
    ]
